apiVersion: v1
kind: Pod
metadata:
  name: app-1
spec:
  containers:
  - name: app-1
    image: centos:7
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim-1

# $ kubectl exec app-1 -- cat /data/out.txt      