apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: app-1  
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-bookworm-perl
          ports:
            - containerPort: 80

---
#load balancer
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: nginx #label is required
  namespace: app-1

spec:
  type: NodePort
  selector:        #same as labels to connect both
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30003